### ISSUE TITLE
Fjerne overflow:hidden i body css?

### ISSUE THREAD

**Issue by thevithach** [FelixKnutsen/HOWWEROLL#20]
overflow:hidden i bodyen gjør det slik at det ikke er mulig å scrolle ned når du har informasjonen som rekker lengre enn skjermens lengde.

**Comment by Lordkissa97** [comment]
på hvilken CSS? alle?

**Comment by Lordkissa97** [comment]
Funker det ikke om man fjerner hidden og setter auto istedenfor?

**Comment by thevithach** [comment]
Mulig auto fungerer, men virker ikke som hidden er veldig funksjonell dersom vi ønsker å scrolle ned.
